### ISSUE TITLE
Heroku Internal Server Error?

### ISSUE THREAD

**Issue by erickyun** [Ryuk-me/Torrent-Api-py#10]
Hi,

I did fork and deploy on heroku but I'm receiving Internal Server Error when I try `https://xxxxxx.herokuapp.com/api/v1/search?site=1337x&query=QxR`

I would appreciate your help with this problem

Edit:
İt seems same problem still occurs for me?

**Comment by forbot002** [comment]
@Ryuk-me 

Could you reopen this issue I problem still occurs?

**Comment by erickyun** [comment]
@Ryuk-me 

Could you reopen the issue The same problem still occurs?

**Comment by Ryuk-me** [comment]
@erickyun https://torrents-api-py3.herokuapp.com/api/v1/search?site=1337x&query=QxR i'm not getting this error 
if u get this error often try hosting it on okteto 4b8bab97e81f71095c0b0d07f8cd669bcf894049

**Comment by erickyun** [comment]
> @erickyun https://torrents-api-py3.herokuapp.com/api/v1/search?site=1337x&query=QxR i'm not getting this error if u get this error often try hosting it on okteto [4b8bab9](https://github.com/Ryuk-me/Torrent-Api-py/commit/4b8bab97e81f71095c0b0d07f8cd669bcf894049)

I dont know why but it works now😅
Sorry for the trouble and thanks for your answer

**Comment by RaXorX** [comment]
@erickyun Is it still working for you? I am getting the same error. I tried putting the app on stating and production both after creating a pipeline but none of it has an effect. I wonder if it's related to heroku having security issues with github oauth since you can't connect to github account from heroku at the moment.
