### ISSUE TITLE
FastApi getting slow

### ISSUE THREAD

**Issue by adarshchri** [Ryuk-me/Torrent-Api-py#56]
The API is so good the work is fabulous 

little issue the API work is so slow on the 

To much slow in 1337x

**Comment by Ryuk-me** [comment]
@adarshchri it's because for every torrent it makes an individual request to scrap its data, let's suppose there are 20 torrents on a page of 1337x to get data related to those torrents, it makes 20 individual requests, which causes it to be slow, whereas in case of Torrent galaxy I get all required data in a single request i.e., why it is faster. 
If you want to make it faster try to change the limit of 1337x https://github.com/Ryuk-me/Torrent-Api-py/blob/aa69ec3e96b30b19a2c8a94cf3a32b97b4586442/helper/is_site_available.py#L39 change it to 20/30 then it'll be little bit faster.
